name: 01-tensor-fundamental
channels:
  - defaults
dependencies:
  - python==3.10.0
  - ipykernel 
  - pip
  - pip:
    - oauthlib==3.2.2
    - protobuf==3.9.2
    - tensorflow==2.10.0
    - tensorflow-cpu==2.10.0
  